name: task_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.5
  day_month_picker: ^1.0.1
  day_night_time_picker: ^1.3.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
